var questions = [{
        "question": "Where is the correct place to insert a script tag?",
        "option1": "Inside the head tag.",
        "option2": "inside the title tag",
        "option3": "At the bottom of the body tag",
        "option4": "none of the above",
        "answer": "3",
    },
    {
        "question": "Which of these are data types in JavaScript?",
        "option1": "Strings",
        "option2": "Numbers",
        "option3": "Booleans",
        "option4": "All  of the above",
        "answer": "4",
    },
    {
        "question": "Is JavaScript case sensitive?",
        "option1": "No",
        "option2": "Yes",
        "option3": "Only at certain times",
        "option4": "Its up to the user",
        "answer": "2",
    },
    {
        "question": "How can you create an array?",
        "option1": "var cat {1,2,3,4,5}",
        "option2": "var cat + [1,2,3,4,5]",
        "option3": "var cat = (1,2,3,4,5)",
        "option4": "var cat = [1,2,3,4,5]",
        "answer": "4",
    },
    {
        "question": "How to give an alert at the top of a page?",
        "option1": "prompt[hello world]",
        "option2": "alert{hello world}",
        "option3": "alert('hello world')",
        "option4": "none of the above",
        "answer": "3",
    },
    {
        "question": "In what ways can you use JavaScript with HTML?",
        "option1": "inline",
        "option2": "internal",
        "option3": "external",
        "option4": "All of the above",
        "answer": "4",
    },
    {
        "question": "How do you console log hello world?",
        "option1": "console.log('hello world')",
        "option2": "consolelog(hello world)",
        "option3": "console log(hello world)",
        "option4": "none of the above",
        "answer": "1",
    }

];